In [ ]:
import numpy

In [2]:
a=numpy.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a[0]

1

In [5]:
a[3]

4

In [8]:
b = numpy.array([[5,6,7,8],[9,10,11,12]])

In [9]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
c=numpy.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])

In [11]:
c

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [12]:
type(a)

numpy.ndarray

In [13]:
type(b)

numpy.ndarray

In [14]:
type(c)

numpy.ndarray

In [15]:
numpy.ndim(a)

1

In [16]:
numpy.ndim(b)

2

In [17]:
numpy.ndim(c)

3

In [18]:
b[0:2]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[0:3]

array([1, 2, 3])

In [20]:
b[1,3]

12

In [22]:
c[0,2,3]

14

In [23]:
a.shape

(4,)

In [24]:
b.shape

(2, 4)

In [25]:
c.shape

(1, 3, 5)

In [26]:
c.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [27]:
c.max()

15

In [28]:
b.min()

5

In [29]:
b.sum(axis=0)

array([14, 16, 18, 20])

In [30]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
numpy.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [33]:
numpy.mean(a)

2.5

In [34]:
numpy.median(a)

2.5

In [35]:
numpy.std(a)

1.118033988749895

In [36]:
numpy.var(a)

1.25

In [37]:
c.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
numpy.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])